### ISSUE TITLE
CNP_CBBA

### ISSUE THREAD

**Issue by knoetherich** [MartinBraquet/task-allocation-auctions#1]
Hello, i get this error message with your project: 
![error_cnp](https://user-images.githubusercontent.com/79964119/203765361-ad636f90-5706-4180-8cd3-9783e4d5c6b3.png)

I think there is one folder missing, isnt it? It would be very nice if you can halp me with this issue. Thanks!

Kind regards 
Knut

**Comment by MartinBraquet** [comment]
@knoetherich Thanks for asking! You probably don't have the latest commit of the code since I renamed the variables in that files a year ago. I just updated the other files as well. Can you clone the repo again and let me know if it still doesn't work?
```
git clone git@github.com:MartinBraquet/task-allocation-auctions.git
``` 
Or simply pull the updates via `git pull origin main`

**Comment by knoetherich** [comment]
Thank you! It works now!
